version: '1.0'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - API_KEY=${API_KEY:?err}
      - AZURE_ENDPOINT=${AZURE_ENDPOINT:?err}
      - AZURE_API_KEY=${AZURE_API_KEY:?err}
      - LOG_LEVEL=INFO
    volumes:
      - ./logs:/app/logs:rw
      - ./config:/app/config:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 15s
      timeout: 20s
      start_period: 10s
      retries: 3
    restart: unless-stopped
    labels:
      - "version=v1.0"